
services:

  database:
    image: mariadb:11.3.2-jammy
    container_name: securefile_db
    volumes:
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3326:3306"
    environment:
      TZ: America/New_York
      MYSQL_ROOT_PASSWORD: P@s5w0rD
      MYSQL_USER: user01
      MYSQL_PASSWORD: P@s5w0rD
      MYSQL_DATABASE: securefile_db

  adminer:
    image: adminer:4.8.1-standalone
    container_name: securefile_adminer
    ports:
      - "8281:8080"
    environment:
      ADMINER_DESIGN: flat
