
services:

  database:
    image: mariadb:11.3.2-jammy
    container_name: securefile_db
    volumes:
      - securefile_db_volume:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3326:3306"
    environment:
      TZ: America/New_York
      MYSQL_ROOT_PASSWORD: P@s5w0rD
      MYSQL_USER: user01
      MYSQL_PASSWORD: P@s5w0rD
      MYSQL_DATABASE: securefile_db

  adminer:
    image: adminer:4.8.1-standalone
    container_name: securefile_adminer
    ports:
      - "8281:8080"
    environment:
      ADMINER_DESIGN: flat

  fileapi:
    image: fileapi
    build:
      context: .
      dockerfile: Dockerfile
    container_name: securefile_api
    volumes:
      - securefile_api_volume:/app/uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=server=securefile_db;port=3306;user=user01;password=P@s5w0rD;database=securefile_db
    depends_on:
      - database
    ports:
      - "8384:8080"

volumes:
  securefile_db_volume:
  securefile_api_volume:
